# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(db_column='Artist_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('background', models.FileField(blank=True, null=True, upload_to='home/uploads/backrgounds/')),
                ('profile', models.FileField(blank=True, null=True, upload_to='home/uploads/profiles/')),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Artist_Follower',
            fields=[
                ('au_id', models.AutoField(db_column='AU_ID', primary_key=True, serialize=False)),
                ('a', models.ForeignKey(blank=True, db_column='A_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
            ],
            options={
                'db_table': 'artist follower',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(db_column='Content_ID', primary_key=True, serialize=False)),
                ('account', models.CharField(db_column='Account', max_length=150)),
                ('ContentType', models.CharField(db_column='Type', max_length=10)),
                ('origin', models.CharField(db_column='Origin', max_length=9)),
                ('content_artist', models.ForeignKey(blank=True, db_column='Content_Artist_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('cultureid', models.AutoField(db_column='CultureID', primary_key=True, serialize=False)),
                ('tag', models.CharField(db_column='Tag', max_length=155)),
            ],
            options={
                'db_table': 'culture',
            },
        ),
        migrations.CreateModel(
            name='Culture_Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_cultureid', models.ForeignKey(blank=True, db_column='Culture_CultureID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Culture')),
            ],
            options={
                'db_table': 'culture_has_festival',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('familyid', models.AutoField(db_column='FamilyID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('festival_artist', models.ForeignKey(blank=True, db_column='Festival_Artist_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('festival_id', models.AutoField(db_column='Festival_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=155)),
                ('start_date', models.DateField(db_column='Start Date')),
                ('end_date', models.DateField(db_column='End Date')),
                ('logo', models.TextField(db_column='Logo')),
                ('background', models.TextField(db_column='Background')),
                ('bio', models.TextField(db_column='Bio')),
            ],
            options={
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='Festival_Artist',
            fields=[
                ('fa_id', models.AutoField(db_column='FA_ID', primary_key=True, serialize=False)),
                ('a', models.ForeignKey(blank=True, db_column='A_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
                ('fl', models.ForeignKey(blank=True, db_column='Fl_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival')),
            ],
            options={
                'db_table': 'festival_artist',
            },
        ),
        migrations.CreateModel(
            name='Festival_Follower',
            fields=[
                ('fu_id', models.AutoField(db_column='FU_ID', primary_key=True, serialize=False)),
                ('f', models.ForeignKey(blank=True, db_column='F_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival')),
            ],
            options={
                'db_table': 'festival follower',
            },
        ),
        migrations.CreateModel(
            name='Festival_Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_festival', models.ForeignKey(blank=True, db_column='Festival_Festival_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival')),
            ],
            options={
                'db_table': 'festival_photographer',
            },
        ),
        migrations.CreateModel(
            name='Festival_Venue',
            fields=[
                ('vf_id', models.AutoField(db_column='VF_ID', primary_key=True, serialize=False)),
                ('f', models.ForeignKey(blank=True, db_column='F_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival')),
            ],
            options={
                'db_table': 'festival_venue',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('identityid', models.AutoField(db_column='IdentityID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
            ],
            options={
                'db_table': 'identity',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_content', models.ForeignKey(blank=True, db_column='Content_Content_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Content')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('linkid', models.AutoField(db_column='LinkID', primary_key=True, serialize=False)),
                ('facebook', models.CharField(blank=True, db_column='Facebook', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, db_column='Instagram', max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, db_column='Youtube', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, db_column='Twitter', max_length=255, null=True)),
                ('spotify', models.CharField(blank=True, db_column='Spotify', max_length=255, null=True)),
                ('soundcloud', models.CharField(blank=True, db_column='Soundcloud', max_length=255, null=True)),
                ('tumblr', models.CharField(blank=True, db_column='Tumblr', max_length=255, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
            ],
            options={
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('photographer_id', models.AutoField(db_column='Photographer_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=150)),
                ('password', models.CharField(db_column='Password', max_length=150)),
                ('email', models.CharField(db_column='Email', max_length=150)),
                ('name', models.CharField(db_column='Name', max_length=64)),
                ('first_name', models.CharField(db_column='First Name', max_length=64)),
                ('last_name', models.CharField(db_column='Last Name', max_length=64)),
                ('bio', models.TextField(db_column='Bio')),
                ('background', models.TextField(db_column='Background')),
                ('profile', models.TextField(db_column='Profile')),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('photographer_family', models.ForeignKey(blank=True, db_column='Photographer_Family_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Family')),
                ('photographer_identity', models.ForeignKey(blank=True, db_column='Photographer_Identity_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Identity')),
                ('photographer_link', models.ForeignKey(blank=True, db_column='Photographer_Link_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Link')),
            ],
            options={
                'db_table': 'photographer',
            },
        ),
        migrations.CreateModel(
            name='Photographer_Artist',
            fields=[
                ('pa_id', models.AutoField(db_column='PA_ID', primary_key=True, serialize=False)),
                ('a', models.ForeignKey(blank=True, db_column='A_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Artist')),
                ('p', models.ForeignKey(blank=True, db_column='P_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Photographer')),
            ],
            options={
                'db_table': 'photographer_artist',
            },
        ),
        migrations.CreateModel(
            name='Photographer_Follower',
            fields=[
                ('up_id', models.AutoField(db_column='UP_ID', primary_key=True, serialize=False)),
                ('p', models.ForeignKey(blank=True, db_column='P_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Photographer')),
            ],
            options={
                'db_table': 'photographer follower',
            },
        ),
        migrations.CreateModel(
            name='Playlist_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_c', models.ForeignKey(blank=True, db_column='Playlist_c_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Content')),
            ],
            options={
                'db_table': 'playlist content',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=64, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=64)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('first_name', models.CharField(db_column='First Name', max_length=64)),
                ('last_name', models.CharField(db_column='Last Name', max_length=64)),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('bio', models.TextField(db_column='Bio')),
                ('profile', models.TextField(db_column='Profile')),
                ('background', models.TextField(db_column='Background')),
                ('user_family', models.ForeignKey(blank=True, db_column='User_Family_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Family')),
                ('user_identity', models.ForeignKey(blank=True, db_column='User_Identity_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Identity')),
                ('user_link', models.ForeignKey(blank=True, db_column='User_Link_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Link')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserPlaylists',
            fields=[
                ('playlistid', models.AutoField(db_column='PlaylistID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('playlist_user', models.ForeignKey(blank=True, db_column='Playlist_User_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User')),
            ],
            options={
                'db_table': 'user playlists',
            },
        ),
        migrations.CreateModel(
            name='UserPlaylists_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_playlists_playlistsid', models.ForeignKey(blank=True, db_column='User Playlists_PlaylistsID', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.UserPlaylists')),
                ('user_user', models.ForeignKey(blank=True, db_column='User_User_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User')),
            ],
            options={
                'db_table': 'user playlists_has_user',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(db_column='Venue_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', default='null', max_length=150)),
                ('city', models.CharField(db_column='City', max_length=155)),
                ('country', models.CharField(db_column='Country', max_length=155)),
                ('state', models.CharField(db_column='State', max_length=155)),
                ('venue_link', models.ForeignKey(blank=True, db_column='Venue_Link_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Link')),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.AddField(
            model_name='playlist_content',
            name='playlist_p',
            field=models.ForeignKey(blank=True, db_column='Playlist_p_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.UserPlaylists'),
        ),
        migrations.AddField(
            model_name='photographer_follower',
            name='u',
            field=models.ForeignKey(blank=True, db_column='U_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_user',
            field=models.ForeignKey(blank=True, db_column='User_User_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User'),
        ),
        migrations.AddField(
            model_name='festival_venue',
            name='v',
            field=models.ForeignKey(blank=True, db_column='V_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Venue'),
        ),
        migrations.AddField(
            model_name='festival_photographer',
            name='photographer_photographer',
            field=models.ForeignKey(blank=True, db_column='Photographer_Photographer_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Photographer'),
        ),
        migrations.AddField(
            model_name='festival_follower',
            name='u',
            field=models.ForeignKey(blank=True, db_column='U_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User'),
        ),
        migrations.AddField(
            model_name='festival',
            name='festival_link',
            field=models.ForeignKey(blank=True, db_column='Festival_Link_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Link'),
        ),
        migrations.AddField(
            model_name='culture_festival',
            name='festival_festival',
            field=models.ForeignKey(blank=True, db_column='Festival_Festival_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_culture',
            field=models.ForeignKey(blank=True, db_column='Content_Culture_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Culture'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_festival',
            field=models.ForeignKey(blank=True, db_column='Content_Festival_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Festival'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_photographer',
            field=models.ForeignKey(blank=True, db_column='Content_Photographer_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Photographer'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_user',
            field=models.ForeignKey(blank=True, db_column='Content_User_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User'),
        ),
        migrations.AddField(
            model_name='artist_follower',
            name='u',
            field=models.ForeignKey(blank=True, db_column='U_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_identity',
            field=models.ForeignKey(blank=True, db_column='Artist_Identity_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Identity'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_link',
            field=models.ForeignKey(blank=True, db_column='Artist_Link_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Link'),
        ),
        migrations.AlterUniqueTogether(
            name='userplaylists_user',
            unique_together=set([('user_playlists_playlistsid', 'user_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='playlist_content',
            unique_together=set([('playlist_p', 'playlist_c')]),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set([('content_content', 'user_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='festival_photographer',
            unique_together=set([('festival_festival', 'photographer_photographer')]),
        ),
        migrations.AlterUniqueTogether(
            name='culture_festival',
            unique_together=set([('culture_cultureid', 'festival_festival')]),
        ),
    ]
