# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='ContentType',
            field=models.CharField(db_column='Type', max_length=55),
        ),
        migrations.AlterField(
            model_name='content',
            name='origin',
            field=models.CharField(db_column='Origin', max_length=55),
        ),
    ]
