# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170416_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='logo',
        ),
        migrations.AddField(
            model_name='festival',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/profiles/'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/backrgounds/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/backrgounds/'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/backrgounds/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='home/uploads/profiles/'),
        ),
    ]
