# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=140, null=True)),
                ('City', models.CharField(blank=True, max_length=140, null=True)),
                ('State', models.CharField(blank=True, max_length=140, null=True)),
                ('Country', models.CharField(blank=True, max_length=140, null=True)),
                ('LinkID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Link')),
            ],
        ),
        migrations.AlterField(
            model_name='photographer',
            name='LinkID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Link'),
        ),
    ]
