# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170416_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival_venue',
            name='f',
        ),
        migrations.RemoveField(
            model_name='festival_venue',
            name='v',
        ),
        migrations.DeleteModel(
            name='Festival_Venue',
        ),
    ]
