# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170416_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='festival_venue',
            field=models.ForeignKey(blank=True, db_column='festival_venue_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Venue'),
        ),
    ]
