# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170302_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('Name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Logo', models.TextField(blank=True, null=True)),
                ('Background', models.TextField(blank=True, null=True)),
                ('LinkID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Link')),
                ('VenueID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Venue')),
            ],
        ),
    ]
