# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_festival_festival_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='bio',
            field=models.TextField(blank=True, db_column='Bio', null=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], db_column='Gender', max_length=1, null=True),
        ),
    ]
