# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('City', models.CharField(blank=True, max_length=140, null=True)),
                ('Country', models.CharField(blank=True, max_length=140, null=True)),
                ('Genre', models.CharField(blank=True, max_length=140, null=True)),
                ('LinkID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Link')),
            ],
        ),
    ]
