# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_festival_artist_festival_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(blank=True, max_length=140, null=True)),
                ('ContentType', models.CharField(blank=True, max_length=140, null=True)),
                ('Source', models.CharField(blank=True, max_length=140, null=True)),
                ('ContentLink', models.TextField(blank=True, null=True)),
                ('FAID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Festival_Artist')),
            ],
        ),
    ]
