# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='Flickr',
            new_name='Soundcloud',
        ),
    ]
