# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170317_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='Background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
