INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('1', 'Arboria');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('2', 'Art');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('3', 'Artist');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('4', 'Body Art');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('5', 'Body Marble');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('6', 'Campgrounds');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('7', 'Dance & Shuffle');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('8', 'Duos People');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('9', 'Fire Dome');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('10', 'Fire Hooper');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('11', 'Fireworks');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('12', 'Flags');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('13', 'Food');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('14', 'Gem');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('15', 'Glass Art');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('16', 'Gloves');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('17', 'Gong Healing');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('18', 'Healers');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('19', 'Jellyfish');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('20', 'Live Art');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('21', 'Media Crew');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('22', 'Misc');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('23', 'Mountains');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('24', 'People');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('25', 'Performers');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('26', 'Pin');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('27', 'Recap');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('28', 'Sacred Grounds');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('29', 'Sign');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('30', 'Silent Disco');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('31', 'Solo People');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('32', 'Speakers');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('33', 'Squads People');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('34', 'Stages');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('35', 'Sunset');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('36', 'Swings');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('37', 'Tents');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('38', 'Totem');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('39', 'Vender');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('40', 'Video Art (Visuals)');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('41', 'Workshops');
INSERT INTO `mydb`.`Culture` (`Culture_ID`, `Tag`) VALUES ('42', 'Yoga');
