INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('1', 'Ambient');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('2', 'Ambient dub');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('3', 'Dark ambient');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('4', 'Drone music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('5', 'Breakbeat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('6', 'Baltimore club');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('7', 'Big beat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('8', 'Breakbeat hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('9', 'Broken beat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('10', 'Florida breaks');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('11', 'Nu-funk');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('12', 'Miami bass');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('13', 'Jersey club');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('14', 'Nu skool breaks');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('15', 'Disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('16', 'Afro/Cosmic disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('17', 'Disco polo');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('18', 'Euro disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('19', 'Italo disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('20', 'Nu-disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('21', 'Space disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('22', 'Downtempo');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('23', 'Acid jazz');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('24', 'Chill-out');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('25', 'Space music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('26', 'Trip hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('27', 'Drum and bass');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('28', 'Darkstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('29', 'Drumstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('30', 'Funkstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('31', 'Hardstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('32', 'Liquid funk');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('33', 'Neurofunk');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('34', 'Neurohop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('35', 'Sambass');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('36', 'Techstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('37', 'Dub');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('38', 'Ambient dub');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('39', 'Dancehall');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('40', 'Dub poetry');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('41', 'Dub reggae');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('42', 'Dub techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('43', 'Dubstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('44', 'Dubtronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('45', 'Electro music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('46', 'Freestyle music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('47', 'Electro swing');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('48', 'Electroacoustic music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('49', 'Acousmatic music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('50', 'Musique concrète');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('51', 'Electronic rock');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('52', 'Alternative dance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('53', 'Indietronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('54', 'Coldwave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('55', 'Dance-punk');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('56', 'Dark wave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('57', 'Electroclash');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('58', 'Electronicore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('59', 'Electropunk');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('60', 'Ethereal wave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('61', 'Krautrock');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('62', 'Minimal wave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('63', 'New rave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('64', 'Nu-gaze');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('65', 'Space rock');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('66', 'Synthpop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('67', 'Synthwave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('68', 'Electronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('69', 'Berlin School');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('70', 'Dubtronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('71', 'Folktronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('72', 'Funktronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('73', 'Laptronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('74', 'Livetronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('75', 'Ethnic electronica');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('76', 'Al Jeel');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('77', 'Arabic pop music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('78', 'Asian underground');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('79', 'Bhangra');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('80', 'Bhangragga');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('81', 'C-pop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('82', 'J-pop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('83', 'K-pop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('84', 'Shibuya-kei');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('85', 'South Asian disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('86', 'Worldbeat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('87', 'Hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('88', 'Gabber');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('89', '4-beat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('90', 'Breakbeat hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('91', 'Bouncy techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('92', 'Breakcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('93', 'Digital hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('94', 'Frenchcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('95', 'Happy hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('96', 'UK hardcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('97', 'Mákina');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('98', 'Speedcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('99', 'Hardstyle');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('100', 'Dubstyle');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('101', 'Jumpstyle');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('102', 'Lento violento');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('103', 'Hi-NRG');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('104', 'Eurobeat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('105', 'Eurodance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('106', 'Bubblegum dance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('107', 'Italo dance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('108', 'Hip hop music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('109', 'Alternative hip hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('110', 'Contemporary R&B');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('111', 'Electro');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('112', 'Electro hip hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('113', 'Gangsta rap');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('114', 'Hardcore hip hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('115', 'Hip house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('116', 'Neo soul');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('117', 'New jack swing');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('118', 'Trap music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('119', 'Trip hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('120', 'UK garage');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('121', 'House music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('122', 'Acid house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('123', 'Ambient house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('124', 'Balearic beat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('125', 'Chicago house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('126', 'Deep house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('127', 'Future house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('128', 'Tropical house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('129', 'Diva house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('130', 'Electro house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('131', 'Big room house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('132', 'Complextro');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('133', 'Fidget house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('134', 'Dutch house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('135', 'Moombahton');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('136', 'Moombahcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('137', 'French house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('138', 'Funky house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('139', 'Garage house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('140', 'Ghetto house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('141', 'Ghettotech');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('142', 'Hardbag');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('143', 'Hard house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('144', 'Hard dance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('145', 'Hard NRG');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('146', 'Hip house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('147', 'Italo house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('148', 'Jazz house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('149', 'Kwaito');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('150', 'Latin house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('151', 'Microhouse/Minimal house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('152', 'New beat');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('153', 'Outsider house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('154', 'Progressive house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('155', 'Rara tech');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('156', 'Tech house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('157', 'Tribal house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('158', 'Trival');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('159', 'Witch house');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('160', 'Industrial music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('161', 'Aggrotech');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('162', 'Electro-industrial');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('163', 'Dark electro');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('164', 'Electronic Body Music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('165', 'Futurepop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('166', 'Industrial metal');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('167', 'Industrial rock');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('168', 'Japanoise');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('169', 'Neue Deutsche Härte');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('170', 'Power electronics');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('171', 'Death industrial');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('172', 'Power noise');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('173', 'IDM');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('174', 'Glitch');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('175', 'Glitch Hop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('176', 'Wonky');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('177', 'Oldschool jungle');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('178', 'Darkcore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('179', 'Ragga jungle');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('180', 'Raggacore');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('181', 'Post-disco');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('182', 'Boogie');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('183', 'Electropop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('184', 'Chillwave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('185', 'Dance-pop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('186', 'Dance-rock');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('187', 'Techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('188', 'Acid techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('189', 'Detroit techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('190', 'Dub techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('191', 'Hardtek/Free tekno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('192', 'Minimal techno');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('193', 'Nortec');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('194', 'Tecno brega');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('195', 'Techdombe');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('196', 'Trance music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('197', 'Acid trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('198', 'Balearic trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('199', 'Dream trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('200', 'Hard trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('201', 'Nitzhonot');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('202', 'Psychedelic trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('203', 'Full on');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('204', 'Suomisaundi');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('205', 'Goa trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('206', 'Progressive trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('207', 'Tech trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('208', 'Uplifting trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('209', 'Vocal trance');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('210', 'Trap');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('211', 'Drill');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('212', 'Future bass');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('213', 'UK garage');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('214', '2-step garage');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('215', 'Dubstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('216', 'Brostep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('217', 'Drumstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('218', 'Chillstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('219', 'Reggaestep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('220', 'Breakstep');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('221', 'Future garage');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('222', 'Grime');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('223', 'Grindie');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('224', 'Speed garage');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('225', 'Bassline');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('226', 'UK funky');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('227', 'Vaporwave');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('228', 'Vaportrap');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('229', 'Future Funk Music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('230', 'Video game music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('231', 'Chiptune');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('232', 'Bitpop');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('233', 'Game Boy music');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('234', 'Skweee');
INSERT INTO `mydb`.`Genre` (`Genre_ID`, `Name`) VALUES ('235', 'Nintendocore');
