INSERT INTO `mydb`.`State` VALUES (NULL, 'Alaska', 'AK');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Alabama', 'AL');
INSERT INTO `mydb`.`State` VALUES (NULL, 'American Samoa', 'AS');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Arizona', 'AZ');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Arkansas', 'AR');
INSERT INTO `mydb`.`State` VALUES (NULL, 'California', 'CA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Colorado', 'CO');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Connecticut', 'CT');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Delaware', 'DE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'District of Columbia', 'DC');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Federated `mydb`.`State` of Micronesia', 'FM');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Florida', 'FL');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Georgia', 'GA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Guam', 'GU');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Hawaii', 'HI');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Idaho', 'ID');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Illinois', 'IL');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Indiana', 'IN');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Iowa', 'IA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Kansas', 'KS');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Kentucky', 'KY');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Louisiana', 'LA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Maine', 'ME');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Marshall Islands', 'MH');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Maryland', 'MD');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Massachusetts', 'MA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Michigan', 'MI');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Minnesota', 'MN');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Mississippi', 'MS');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Missouri', 'MO');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Montana', 'MT');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Nebraska', 'NE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Nevada', 'NV');
INSERT INTO `mydb`.`State` VALUES (NULL, 'New Hampshire', 'NH');
INSERT INTO `mydb`.`State` VALUES (NULL, 'New Jersey', 'NJ');
INSERT INTO `mydb`.`State` VALUES (NULL, 'New Mexico', 'NM');
INSERT INTO `mydb`.`State` VALUES (NULL, 'New York', 'NY');
INSERT INTO `mydb`.`State` VALUES (NULL, 'North Carolina', 'NC');
INSERT INTO `mydb`.`State` VALUES (NULL, 'North Dakota', 'ND');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Northern Mariana Islands', 'MP');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Ohio', 'OH');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Oklahoma', 'OK');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Oregon', 'OR');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Palau', 'PW');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Pennsylvania', 'PA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Puerto Rico', 'PR');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Rhode Island', 'RI');
INSERT INTO `mydb`.`State` VALUES (NULL, 'South Carolina', 'SC');
INSERT INTO `mydb`.`State` VALUES (NULL, 'South Dakota', 'SD');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Tennessee', 'TN');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Texas', 'TX');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Utah', 'UT');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Vermont', 'VT');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Virgin Islands', 'VI');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Virginia', 'VA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Washington', 'WA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'West Virginia', 'WV');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Wisconsin', 'WI');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Wyoming', 'WY');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Africa', 'AE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Americas (except Canada)', 'AA');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Canada', 'AE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Europe', 'AE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Middle East', 'AE');
INSERT INTO `mydb`.`State` VALUES (NULL, 'Armed Forces Pacific', 'AP');